Dockerfile
	1. Dockerfile is basically a text file. It contains some set of instructions.
	2. Automation of docker image creation.

Dockerfile components
FROM 	 For base/parent image. This command is on the top of the dockerfile.
RUN 	To execute commands while image creation, for additional dependencies it will create a layer in image.
MAINTAINER	Author/Owner/Description
COPY	Copy files from local system (docker VM), we need to provide source, destination (we can't download file from the internet and any repo)
VOLUME	Creating a volume in the container
ADD	Similar to COPY it provides feature to download files from internet, also we extract file at docker image side. If the file is zipped, it unzips it also.
EXPOSE	To export ports such as port 8080 for tomcat
WORKDIR	To set the working directory for a container
CMD	Execute commands but during container creation
ENTRYPOINT	Similar to CMD, but has higher priority over CMD, first commands in ENTRYPOINT will be executed.
ENV	Environment Variables
ARG	

You can insert comments in your Dockerfile using #